<a href="https://colab.research.google.com/github/Touchfree-Labz/deeplearning-with-pytorch/blob/main/tensor_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [8]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# re-shape and view
my_torch2 = my_torch.reshape(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# when we don't know the count reshape using -1
my_torch3 = my_torch.reshape(2,-1)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch4 = torch.arange(15)
my_torch4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
my_torch4 = my_torch4.reshape(3,-1)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [18]:
my_torch4 = my_torch4.view(3,-1)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [19]:
my_torch5 = torch.arange(15)
my_torch5

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
my_torch6 = my_torch5.reshape(3,5)
my_torch6

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [21]:
# update original tensor
my_torch5[1] = 999

In [23]:
# after applying the change re-shaped tensor also updated
my_torch6

tensor([[  0, 999,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]])

In [24]:
# slices tensor
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# grab singles
my_torch7[7]

tensor(7)

In [28]:
my_torch8 = my_torch7.reshape(5,-1)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [36]:
# grab slice
# my_torch8[2,:] # third row.
# my_torch8[-1,:] # last row
my_torch8[:,0] # first column
# my_torch8[:,-1] # last column

tensor([8, 9])