<a href="https://colab.research.google.com/github/Touchfree-Labz/deeplearning-with-pytorch/blob/main/tensor_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATION**


*   add, subtract, multiply, devide, remainter and exponent
*   shorthand and uh, longhand
*   re-assignment


In [2]:
import torch
import numpy as np

In [13]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [9]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [14]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
# subtraction
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [17]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [18]:
# multiply
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [19]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [20]:
# division
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [21]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [23]:
# remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [24]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [25]:
# exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [26]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [29]:
# reassignment
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [30]:
tensor_a

tensor([ 6,  8, 10, 12])