<a href="https://colab.research.google.com/github/Touchfree-Labz/deeplearning-with-pytorch/blob/main/tensors_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**


*   tensors are multi-diamentional arrays
*   similar to numpy arrays and works better on GPUs than numpy arrays
*   default data type is float32
*   more suitable for deep learning than numpy arrays





In [3]:
import torch
import numpy as np

**LISTS**

In [5]:
my_list = [[1,2,3,4,5],[1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

**NUMPY ARRAY**

In [6]:
np_array1 = np.random.rand(3,4)
np_array1

array([[0.80920985, 0.11533216, 0.48111757, 0.31296903],
       [0.78266104, 0.25531092, 0.08339319, 0.33590054],
       [0.75809434, 0.38911761, 0.27940083, 0.83559   ]])

In [9]:
np_array1.dtype

dtype('float64')

**TENSORS**

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.2006, -0.1168,  1.2085,  1.3937],
        [-0.8932,  1.1368, -1.7049, -0.4270],
        [-0.1154, -1.0412,  0.1321, -0.5103]])

In [11]:
tensor_2d.dtype

torch.float32

In [12]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
# create tensor out of numpy array
my_tensor = torch.tensor(np_array1)
my_tensor

tensor([[0.8092, 0.1153, 0.4811, 0.3130],
        [0.7827, 0.2553, 0.0834, 0.3359],
        [0.7581, 0.3891, 0.2794, 0.8356]], dtype=torch.float64)

In [14]:
my_tensor.dtype

torch.float64